### ISSUE TITLE
want to reach out to you.....

### ISSUE THREAD

**Issue by alokVerma749** [diveshthakre19/crud_app#1]
Hi divesh I am looking for any contact link, but i didn't find any. can you provide your email, just wanted to connect with you.
I know this is not a way to reach out to someone.....apologies

**Comment by diveshthakre19** [comment]
diveshthakre20@gmail.com

**Comment by diveshthakre19** [comment]
> Hi divesh I am looking for any contact link, but i didn't find any. can you provide your email, just wanted to connect with you. I know this is not a way to reach out to someone.....apologies

diveshthakre20@gmail.com
